mybatis-flex:
  datasource:
    mysql:
      url: jdbc:mysql://116.62.152.145:3006/exam-dev?serverTimezone=Asia/Shanghai&timezone=GMT+8&useUnicode=true&characterEncoding=utf-8
      username: exam-dev
      password: exam2025
      type: com.alibaba.druid.pool.DruidDataSource
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
