
server:
  port: 8000
  servlet:
    context-path: /api

spring:
  application:
    name: medical-exam-system

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev

mybatis-flex:
  mapper-locations: classpath*:/mapper/*.xml
#  type-aliases-package: com.medical.exam.entity
  configuration:
    default-statement-timeout: 500
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    call-setters-on-nulls: true
#    jdbc-type-for-null: 'null'
#
#logging:
#  level:
#    com.medical.exam: debug
#    org.springframework.security: debug

jwt:
  secret: medical-exam-system-secret-key-2024
  expiration: 86400000 # 24 hours
