mybatis-flex:
  datasource:
    mysql:
      url: jdbc:mysql://47.106.181.244:3306/ai_deepservice_test?serverTimezone=Asia/Shanghai&timezone=GMT+8&useUnicode=true&characterEncoding=utf-8
      username: ai
      password: T3w@W96xANvLRcx
      type: com.alibaba.druid.pool.DruidDataSource
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
